site_name: Intelligent Textbook v1
repo_url: https://github.com/btlepak/i-book-v1
nav:
  - Home: index.md
  - Course Description: cd.md
  - List of Chapters:
    - Programs and Processes: chapters/1_PandP/index.md
    - I/O Basics & Redirection: chapters/2_io/index.md
    - File Systems: chapters/3_fs/index.md
    - Virtual Memory: chapters/4_vm/index.md
    - Signals: chapters/5_signals/index.md
    - Pipes: chapters/6_pipes/index.md
    - Shared Memory: chapters/7_sm/index.md
    - Sockets and Communication: chapters/8_SandC/index.md
    - TCP & UDP: chapters/9_tcpudp/index.md
    - Threads: chapters/10_threads/index.md
  - Projects:
    - Project 1: projects/proj1.md
  - Sims: 
    - Learning Graph: sims/learning-graph/index.md
    - Word Cloud: sims/wordcloud/index.md
    - Process Tree: sims/process-tree/index.md
    - File System Access: sims/file-system-access/index.md
    - Virtual Memory Mapping: sims/virtual-memory-mapping/index.md
  - Glossary: glossary.md
  - References: references.md
  - Contact: contact.md

extra_javascript:
  - sims/stack_memory.html

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed

theme:
  name: material
