site_name: Intelligent Textbook v1
repo_url: https://github.com/btlepak/i-book-v1
nav:
  - Home: index.md
  - Course Description: cd.md
  - List of Chapters:
    - Introduction: chapters/1-intro.md
    - Operating Systems Overview: chapters/2-overview.md
    - Programs and Processes: chapters/3-PandP.md
    - I/O Basics & Redirection: chapters/4-io.md
    - File Systems: chapters/5-fs.md
    - Virtual Memory: chapters/6-vm.md
    - Signals: chapters/7-signals.md
    - Pipes: chapters/8-pipes.md
    - Shared Memory: chapters/9-sm.md
    - Sockets and Communication: chapters/10-SandC.md
    - TCP & UDP: chapters/11-tcpudp.md
    - Threads: chapters/12-threads.md
  - Projects:
    - Project 1: projects/proj1.md
    - Project 2: projects/proj2.md
    - Project 3: projects/proj3.md
    - Project 4: projects/proj4.md
  - Prompts: 
    - Prompt 1: prompts/prompt1.md
  - MircoSims: microSims/index.md
  - Contact: contact.md

extra_javascript:
  - microSims/stack_memory.html

theme:
  name: material
